# [target.aarch64-unknown-linux-gnu]
# linker = "aarch64-linux-gnu-gcc"

[target.mipsel-unknown-linux-gnu]
linker = "mipsel-linux-gnu-gcc"
rustflags = [
    "-C", "target-cpu=mips32r2",
    "-C", "link-arg=-EL"  # Ensures little-endian output
]
